### ISSUE TITLE
[DB] menu option 테이블 추가 

### ISSUE THREAD

**Issue by EunjiShin** [Techeer-TeamB/Telivery#13]
## 📌 논의 사항

menu option 테이블을 추가로 설계합니다. 

<br>

## 🤝 결정 사항

주문시 메뉴 옵션 선택하기 기능을 개발하기로 결정했습니다.
(Ex. 볶음밥 메뉴 주문 -> 현미밥, 쌀밥, 흑미밥 중 선택)

<br>

## 🧐 고려 사항

없습니다. 

<br>

### ✅ 참고 사항
![image](https://user-images.githubusercontent.com/38103085/162620609-2ec71ea7-066e-4619-8ea3-7cd3141e96dc.png)

**Comment by Zzyoon** [comment]
Table menu_option{
  id int [pk]
  menuId int [ref: > M.id]
  type tinyint //필수0 추가1
  optionname varchar[50]
  price int //추가금액
  created_at timestamp
  updated_at timestamp
}
