### ISSUE TITLE
[SETTING] Telivery 시스템 아키텍처 설계 

### ISSUE THREAD

**Issue by EunjiShin** [Techeer-TeamB/Telivery#5]
- Telivery 서비스의 시스템 아키텍처를 설계합니다. 
  - 개발 기능, 사용해보고 싶은 기술 스택 등을 종합하여 제안합니다.

**Comment by junhyeongkim2** [comment]
<img width="1441" alt="스크린샷 2022-04-10 오후 3 41 19" src="https://user-images.githubusercontent.com/52617204/162605818-16d6b2fd-66e5-4dd7-ada0-b8e817942cb1.png">

**Comment by Zzyoon** [comment]
![Teacher_System Architecture! 001](https://user-images.githubusercontent.com/98005864/163576114-dcbcac5d-c2e7-4d1e-bb92-16583a1aa970.jpeg)

**Comment by EunjiShin** [comment]
- docker 컨테이너 화 
- CI/CD 툴 아키텍처 수정

**Comment by Zzyoon** [comment]
![0430teacher_architecture 001](https://user-images.githubusercontent.com/98005864/166106713-c4695a3c-2570-414e-a9d5-867d9c6c0cda.jpeg)
![0430teacher_architecture 002](https://user-images.githubusercontent.com/98005864/166106716-4b4df467-f728-48d4-8231-61140f245a63.jpeg)
