### ISSUE TITLE
[API] 도메인별 REST API 설계하기 

### ISSUE THREAD

**Issue by EunjiShin** [Techeer-TeamB/Telivery#6]
## 📌 Description
> 요구사항을 반영하여 도메인별 필요 API를 구상합니다. 

## 🔍 Progress
> 테이블명은 추후 변경될 수 있습니다 (임시)
- [x] account
- [x] restaurant
- [x] menu
- [x] bookmark
- [x] order
- [x] review

**Comment by junhyeongkim2** [comment]
https://www.notion.so/Telivery-e3df887287764911bd227f397fb1094b - x

https://powerful-throne-65d.notion.site/Telivery-e3df887287764911bd227f397fb1094b - o

**Comment by HyunTaek5** [comment]
https://invincible-armchair-3e7.notion.site/Telivery-acc8b6e37db04e2ca50338235f89b13c

**Comment by jadechoi** [comment]
https://lumpy-skipjack-9f1.notion.site/Telivery-8041544565b042be8eb121f6d1ef7f5d

**Comment by su-aJ815** [comment]
https://ubiquitous-practice-e72.notion.site/Telivery-c9d9fefc57f24c519b059dfbe90b9bd5

**Comment by Zzyoon** [comment]
https://peridot-llama-d0c.notion.site/39d8eb1ecd4443bb9c7a8ef77533d291?v=d5d54f6c061d48e6be6a23ce5095da12

**Comment by EunjiShin** [comment]
https://bronzed-chameleon-251.notion.site/92841a0aaa3e42ee8565cbe59c24c26f?v=03f223c17fa54abc8781e965fc12666a

**Comment by EunjiShin** [comment]
@HyunTaek5 
세션 방식으로 진행하기로 결정되었으므로 API 업데이트 부탁드리겠습니다 ^.ㅜ 
죄송하고...감사합니다...!!

**Comment by EunjiShin** [comment]
@Techeer-TeamB/techeer-teamb 
API 버전 관리를 위해, 모든 REST API에 `"/api/v1" prefix`를 붙이기로 구두로 협의하였습니다.
